### ISSUE TITLE
no data at the boiler entities

### ISSUE THREAD

**Issue by jboesh** [cyberjunky/home-assistant-toon_boilerstatus#17]
Hi

I followed the instructions (installed the boiler app in the toon store, also installed your extension in HACS.
including this part in the configuration file, like this:

```
  - platform: toon_boilerstatus
    name: Toon
    host: toon-ip-address
    port: 80
    scan_interval: 10
    resources:
      - boilersetpoint
      - boilerintemp
      - boilerouttemp
      - boilerpressure
      - boilermodulationlevel
      - roomtemp
      - roomtempsetpoint
```
after a restart of home asisstant, I see the entities showing up but nothing is happening. I dont see any data.
for instance
![image](https://user-images.githubusercontent.com/71582854/198044479-379b7157-9aed-48b1-8c3d-d8499f0a209b.png)

Any ideas how to fix this? what am I missing?

Iam using the latest version of Home assistant, also the latest version of your extension.

The CV I have: 
Intergas Kombi Kompakt HR 28/24 HR Combiketel 6,9 - 22,6 kW CW4
this has the opentherm option so far as I know.

Thanks!
