### ISSUE TITLE
Unable to override the entity friendly name

### ISSUE THREAD

**Issue by djansen1987** [cyberjunky/home-assistant-toon_boilerstatus#8]
Hi, 

I was wondering if it is possible to override the entity friendly name.
If i would do so now. It gets back it default name after the next Polling of info.

The reason is that it won't fit for me.

![image](https://user-images.githubusercontent.com/20375973/111283253-37133780-863f-11eb-933b-c0cc544bf234.png)

**Comment by cyberjunky** [comment]
@djansen1987 Hi, thanks for reporting, I just checked the code, and don't see something strange at first sight, what does your config look like?

**Comment by djansen1987** [comment]
Hi

This is my boiler setup:

```
- platform: toon_boilerstatus
  host: 192.168.X.X
  port: 10080
  scan_interval: 10
  resources:
    - boilersetpoint
    - boilerintemp
    - boilerouttemp
    - boilerpressure
    - boilermodulationlevel
    - roomtemp
    - roomtempsetpoint
```

when saving the customization of the friendly name:
![image](https://user-images.githubusercontent.com/20375973/111993478-f58afc80-8b16-11eb-80b4-283975ac5f7b.png)

10 seconds later it revert back
![image](https://user-images.githubusercontent.com/20375973/111993544-076c9f80-8b17-11eb-9d06-f8e1310961ef.png)

this can be reproduced by clicking save on the customization
